package vn.sunbuy.storyapi.common;

public class URI {
	public static final String V1 = "/v1";
	public static final String USERS = "/users";
	public static final String API = "/api";
	public static final String AUTHOR = "/author";
	public static final String CATEGORY = "/category";
	public static final String CHAPTER = "/chapter";
	public static final String ID = "/{id}";
	public static final String ADMIN = "/admin";
	public static final String GETSTORYBYAUTHORNAME = "/{author}";
	public static final String AUTH = "/auth";
	public static final String GETALL = "/getAll";
	public static final String STORY = "/story";
	public static final String UPDATE = "/update";
	public static final String SIGNUP = "/signup";
	public static final String SIGNIN = "/signin";
	public static final String PROFILE = "/profile";
	public static final String PASSWORD = "/change-password";
	public static final String CATEGORYCODE = "/{categoryCode}";
	public static final String LOGIN = "/login";
	public static final String CREATE = "/create";
	public static final String SUCCESS = "/success";
	public static final String FILTERBYCHAPTERS = "/so-chuong/{range}";
	public static final String HOME = "/home";
	public static final String GETNEWSTORIES = "/getNewStories";
	public static final String GETCOMPLETEDSTORIES = "/getCompletedStories";
	public static final String GETSTORYBYCATEGORY = "/getStoryByCategory";
	public static final String GETTOPSTORYBYCATEGORY ="/getTopStoryByCategory";
	public static final String SEARCH = "/search";
	public static final String GETSTORYDETAIL = "/{storyCode}";
	public static final String FILTER = "/{filter}";
	public static final String UPDATEORCREATEVIEW = "/updateOrCreateView";
	public static final String GETTOPDAY = "/top-stories";
	public static final String GETTOPMONTH = "/getTopMonth";
	public static final String GETTOPYEAR = "/getTopYear";
	public static final String GETCONTENSTORY = "/{storyCode}/chuong-{chapterNumber}";
	public static final String UPLOADFILE = "/uploadFile";
	public static final String UPLOADMULTIPLEFILES = "/uploadMultipleFIles";
	public static final String DOWNLOADFILE = "/downloadFile";
	public static final String FILENAME = "/{fileName}";
	public static final String USER = "/user";
	public static final String LIST = "/list";
	public static final String CONFIRM = "/confirm";
	public static final String RETURN = "/return";
	public static final String RESOURCE = "/resource";	
}